### ISSUE TITLE
License

### ISSUE THREAD

**Issue by meisam-wiki** [Kizoky/Mr_SmileyII#5]
Please choose a license for this repository. (I hope all the assets in this version are under a free license!)

**Comment by Kizoky** [comment]
Hi!
All the assets from this repo are free, however please credit me (or the mod's name: Mr. Smiley Head's Safari II) that's all I ask

**Comment by meisam-wiki** [comment]
Please choose a proper license and add it to the repo. Please read https://help.github.com/en/articles/licensing-a-repository
This guide also may help you choose: https://choosealicense.com/

**Comment by Kizoky** [comment]
Honestly I don't ever recall a Doom mod or wad ever having a license, other than for code
+ The problem is this mod has assets from other mods, the content in this mod isn't 100% made by me
